name: Manual VM Checkpoint

on:
  workflow_dispatch:

jobs:
  checkpoint-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Checkpoint Script
      run: ./scripts/checkpoint
