#!/usr/bin/env python3

import boto3
import json
import os
import sys

def get_b2_client_and_bucket():
    config_path = os.path.join(os.path.dirname(__file__), '..', 'config', 'storage.json')
    with open(config_path, 'r') as f:
        config = json.load(f)

    session = boto3.session.Session()
    s3_client = session.client(
        service_name='s3',
        region_name='us-east-001',  # Backblaze B2 region, can be anything for S3 compatible API
        endpoint_url=config['endpoint'],
        aws_access_key_id=config['key_id'],
        aws_secret_access_key=config['application_key']
    )
    return s3_client, config['bucket_name']

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./backblaze/upload <file_path>")
        sys.exit(1)

    file_path = sys.argv[1]
    file_name = os.path.basename(file_path)

    try:
        s3_client, bucket_name = get_b2_client_and_bucket()
        print(f"Uploading {file_name} to bucket {bucket_name}...")
        s3_client.upload_file(file_path, bucket_name, file_name)
        print(f"Successfully uploaded {file_name}.")
    except Exception as e:
        print(f"Upload failed: {e}")
        sys.exit(1)
